"""add replanned status

Revision ID: 10fd5ec1d1da
Revises: 4cd1b26013ec
Create Date: 2026-03-22 19:24:39.587984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10fd5ec1d1da'
down_revision: Union[str, Sequence[str], None] = '4cd1b26013ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE \"EventStatus\" ADD VALUE 'replanned';")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
