"""add due_date to event

Revision ID: 4cd1b26013ec
Revises: c27549da72c7
Create Date: 2026-02-22 17:46:50.203878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cd1b26013ec'
down_revision: Union[str, Sequence[str], None] = 'c27549da72c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('due_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'due_date')
    # ### end Alembic commands ###
